**NumPy Arrays**


***Import the module***


In [ ]:
import numpy as np


***Create 1D and 2D arrays***


In [3]:
import numpy as np

#1-D array
a = np.array([23, 45, 21, 53])
print("1D array:", a)

#2-D array
b = np.array([[32, 43, 54, 65], [12, 34, 56, 78]])
print("2D array:\n", b)

1D array: [23 45 21 53]
2D array:
 [[32 43 54 65]
 [12 34 56 78]]



***Check shape, size, datatype***


In [6]:
import numpy as np

b = np.array([[32, 43, 54, 65], [12, 34, 56, 78]])
print("Shape:", np.shape(b))
print("Size:", np.size(b))
print("Datatype:", np.dtype)

Shape: (2, 4)
Size: 8
Datatype: <class 'numpy.dtype'>



***Indexing & slicing***


In [13]:
#indexing
print(a[1])
print(b[1])
print(b[1][2])

#slicing
print(a[0:2])
print(b[::])
print()
print(b[:, 1])

45
[12 34 56 78]
56
[23 45]
[[32 43 54 65]
 [12 34 56 78]]

[43 34]



**Operations**

***Addition, subtraction, multiplication***


In [15]:
import numpy as np

a = np.array([2, 4, 6, 9, 10])
b = np.array([1, 3, 5, 7, 8])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)

Addition: [ 3  7 11 16 18]
Subtraction: [1 1 1 2 2]
Multiplication: [ 2 12 30 63 80]



***Aggregate Functions***


In [16]:
import numpy as np

a = np.array([2, 4, 6, 9, 10])
print("Sum:", np.sum(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))
print("Mean:", np.mean(a))

Sum: 31
Minimum: 2
Maximum: 10
Mean: 6.2
